# Generated by Django 3.1.1 on 2020-09-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='add_to_calendar',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
