# Generated by Django 3.1.1 on 2020-09-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_add_to_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='add_to_calendar',
        ),
    ]
