# Generated by Django 3.1.1 on 2020-11-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
